# This is a basic workflow to help you get started with Actions

name: auto_commit

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
  schedule:
    # * is a special character in YAML so you have to quote this string
    # runs at minute 8 of the 8th hour of every day.
    - cron:  '8 8 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo auto create one commit

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          npm run create_one_commit
