# This is a basic workflow to help you get started with Actions

# workflow name
name: 🚀 DevOps 👻 CI/CD

# workflow 触发事件, 控制 action 何时运行
# 在 push 或 pull 请求时触发工作流程事件，但仅针对 master & main 分支
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

# 一个 workflow 运行由可以串行或并行运行的一个或多个 jobs 组成
jobs:
  # 此工作流程仅包含一个名为 "build_job" 的 job
  build_job:
    # job 将运行的 runner 类型(执行的系统环境 Linux 👍/ macOS 🚀/ Windows 👎)
    runs-on: ubuntu-latest
    
    # 一个 job 可以包含多个 steps
    # 步骤表示将作为 job 一部分执行的一系列 tasks
    steps:
      # 在 $GITHUB_WORKSPACE 下检出你的 repository，以便你的 job 可以访问它
      # uses 使用第三方的 actions
      - uses: actions/checkout@v2
      
      # uses 使用第一方的 actions，自定义的 actions
      - uses: ./actions
        with:
          MY_NAME: "xgqfrms"
          TOKEN: "$ACCESS_TOKEN"
      
      # with & env
      - name: access_token action
        with: # Set the secret as an input
          access_token: ${{ secrets.ACCESS_TOKEN }}
        env: # Or as an environment variable
          access_token: ${{ secrets.ACCESS_TOKEN }}

      # 使用 runners shell 运行单个命令 
      - name: Run a one-line script ✅ 👨🏻‍💻
        run: echo 正在执行单个命令! 

      # 使用 runners shell 运行一组命令
      - name: Run a multi-line script ✅ 👨🏻‍💻
        run: |
          echo 正在执行多个命令的 lint
          echo 正在执行多个命令的 test
          echo 正在执行多个命令的 build
          echo 正在执行多个命令的 deploy
          echo 正在执行多个命令的 npm publish
          echo finished 🎉
